# Generated by Django 3.2.3 on 2021-05-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20210531_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eap',
        ),
    ]
