# Generated by Django 3.2.3 on 2021-05-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_employeedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='bitcoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTC_BUSD', models.FloatField()),
                ('USD_INR', models.FloatField()),
                ('WRX_BTC_INR', models.FloatField()),
                ('BIN_BTC_INR', models.FloatField()),
                ('PROFIT_BTCINR', models.FloatField()),
                ('PROFIT_PERC', models.FloatField()),
                ('datetime_ist', models.FloatField()),
            ],
            options={
                'db_table': 'price',
            },
        ),
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
    ]
