# Generated by Django 3.2.3 on 2021-06-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20210531_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=250)),
                ('datatime', models.DateField()),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
