# Generated by Django 3.2.3 on 2021-06-20 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_register'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bitcoin',
            table=None,
        ),
        migrations.AlterModelTable(
            name='register',
            table=None,
        ),
    ]
