# Generated by Django 3.2.3 on 2021-06-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20210620_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='bitcoin',
            table='price',
        ),
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
