# Generated by Django 3.2.3 on 2021-06-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_auto_20210620_1057'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bitcoin',
            table='price1',
        ),
    ]
